name: Build Test Deploy

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest coverage-badge
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest coverage-badge
          pip install -r requirements.txt

      - name: Create badges and report directory
        run: |
          mkdir -p .github/badges
          mkdir -p docs/coverage_html_report

      - name: Run tests and generate coverage
        run: |
          coverage run --parallel -m pytest
          coverage combine
          coverage report
          coverage html -d docs/coverage_html_report
          coverage-badge -o .github/badges/coverage.svg -f

      - name: Upload coverage as artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: |
            .github/badges/coverage.svg
            docs/coverage_html_report/

  deploy:
    runs-on: ubuntu-latest
    needs: test # сначала выполняется test
    steps:
      - uses: actions/checkout@v2

      - name: Commit coverage badge and report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/badges/coverage.svg docs/coverage_html_report/ docs/index.html
          git commit -m "CI/CD badges" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
